
server:
  port: 3000
spring:
  application:
    name: appointmentservice
  datasource:
    url: jdbc:mysql://localhost:3306/dental
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true